### PR TITLE
Added Ada Lovelace Day

### PR DESCRIPTION
**Pull request by lightwavefeesh**
This pull request adds the site and a short description for Ada Lovelace Day, an international holiday for celebrating the contributions of women in science, technology, engineering, and mathematics fields.

\* I'm not sure whether this goes under the General or Content category as both sections contain participation events.

### CODE REVIEW

**Comment by harsh183** [comment]
Thanks for the pull request! I think the 'Meetups/Events' category might be good for this one. @cristianoliveira what do you think?

Also, in the future, make your your commits follow a format similar to http://seesparkbox.com/foundry/semantic_commit_messages. (Well I've broken that I couple of times :P, but you get the point.

**Comment by cristianoliveira** [comment]
> Thanks for the pull request! I think the 'Meetups/Events' category might be good for this one. @cristianoliveira what do you think?

It is there already `Meetups/Events > General` 😄

> Also, in the future, make your commits follow a format similar to http://seesparkbox.com/foundry/semantic_commit_messages. (Well I've broken that I couple of times :P, but you get the point.)

Exactly. Although we can always squish and merge with another commit message. But then we lose the original commit messages. 😞 
So If you want to have all your commits merged using the original messages you must follow the "semantic commit" pattern 😄

**Comment by harsh183** [comment]
@lightwavefeesh Can you move it to the Meetups/Events category?

**Comment by cristianoliveira** [comment]
> @lightwavefeesh Can you move it to the Meetups/Events category?

Actually, It's already under `Meetups/Events`. It under `Meetups/Events > General`

**Comment by harsh183** [comment]
Oh whoops I missed that 😛

**Pull request merged**
