### PR TITLE
[Initiatives/Programs]: Added TechLadies Brasil

### PR DESCRIPTION
**Pull request by astronomaelaine**
[Initiatives/Programs]: Added TechLadies Brasil

### CODE REVIEW

**Comment by cristianoliveira** [comment]
Hello @astronomaelaine thanks for adding Techladies Brasil. :)

You've added it under "Academy/Camp" looking at their website I couldn't find their academy or camp. Don't you think it fits better under "General"?

**Comment by astronomaelaine** [comment]
Absolutely. My mistake. I actually thought of putting in general, but I just wrote in the wrong category.

**Comment by cristianoliveira** [comment]
Looks like it is not in the right order (build failed). Could you please change its order?

Right order:
"ada lovelace day", "bay area girls", "byte girl", "code girl", "fortune most powerful women summit", "league of women coders", "rodada hacker", "tech ladies brasil", "technovation", "women of silicon roundabout", "women who code", "wonder women tech summit"

**Comment by cristianoliveira** [comment]
Thanks! ;)

**Pull request merged**
