### PR TITLE
chores: add anitas.com.br

### PR DESCRIPTION
**Pull request by deboraazevedo**
solving issue #44

### CODE REVIEW

**Comment by harsh183** [comment]
I just fixed the url, once the build is passing we'll add it. Thanks a lot for your contribution and getting in touch with them.

**Comment by harsh183** [comment]
@cristianoliveira  Looks like the spec passed after I removed one trailing space after the period. I suggest using `String#strip`

Here: https://github.com/cristianoliveira/awesome4girls/pull/140

**Comment by cristianoliveira** [comment]
Hey @deboraazevedo Thanks for your contributions!

> @cristianoliveira Looks like the spec passed after I removed one trailing space after the period. I suggest using String#strip

Actually, it supposed to not have trailing spaces as mentioned in https://github.com/cristianoliveira/awesome4girls/blob/master/CONTRIBUTING.md

What we can do is improve the error message for such errors.

**Comment by cristianoliveira** [comment]
Added a new spec for this: https://github.com/cristianoliveira/awesome4girls/commit/cb304c48fa3d1cadb28a9fa7cf73fb4bf7e2aba2

Now it has a proper fail message :)

**Pull request merged**
