### PR TITLE
Creates index and adds conf

### PR DESCRIPTION
**Pull request by annesoares**
Hi!

Since this is such a big README, I thought maybe adding a Table of Contents with links would make it easier to browse =) I also added "Go to top" links, around the same goal.

And a commit adding a new conference!

### CODE REVIEW

**Comment by harsh183** [comment]
I was just about to suggest an issue regarding the same, it was starting to get unwieldy. Did you use a tool for it, or made it manually. Either way. I'm merging. 

Great contribution!

**Comment by harsh183** [comment]
You left a tiny bug, https://github.com/cristianoliveira/awesome4girls/pull/83.

Don't worry, I fixed it :) 

Looking forward to more contributions from you in the future.

**Comment by annesoares** [comment]
Sorry! I completely forgot to test index after I added the "Go to top" links 🤒 

Thank you and great job with this awesome! ❤️

**Comment by cristianoliveira** [comment]
OMG 




Thanks,  you are awesome!

**Pull request merged**
